UPDATE_ORDNER_NAME_APP = "updates"
UPDATE_ORDNER_NAME_USER = "Updates"
BASE_DIR = "{{ cookiecutter.app_name|lower|replace('-', '_') }}"
ARCHIV_ORDNER = "Archive"
KUNDENDATEN_ORDNER_APP = "kundendaten"
SETTINGS_ORDNER = "Settings"