name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.X"
    - name: Install dependencies
      run: |
        python -m pip install tox
    - name: Test with tox
      run: |
        tox

  verify-apps:
    name: Build App
    needs: unit-tests
    uses: beeware/.github/.github/workflows/app-build-verify.yml@main
    with:
      # This *must* be the version of Python that is the native system Python on
      # ubuntu-22.04, which is needed to test local Debian packages. We use
      # ubuntu-22.04 explicitly rather than ubuntu-latest because when
      # ubuntu-latest upgrades to ubuntu-24.04, it will happen gradually, so the
      # system Python version won't be predictable.
      python-version: "3.10"
      briefcase-template-source: "../../"
      runner-os: ${{ matrix.runner-os }}
      framework: ${{ matrix.framework }}
    strategy:
      fail-fast: false
      matrix:
        framework: [ "toga", "pyside2", "pyside6", "ppb", "pygame" ]
        runner-os: [ "macos-latest", "ubuntu-22.04", "windows-latest" ]
